# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hairfolio' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for Hairfolio
    rn_path = '../node_modules/react-native'
    pod 'Yoga', path: "#{rn_path}/ReactCommon/yoga/Yoga.podspec"
    
    pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
    ]
    
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/Core'
    pod 'AFNetworking'
    pod 'SAMKeychain'
    pod 'DYQRCodeDecoder'
    pod 'QRCode'
   
end


# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end



