# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.35.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Build an ipa"
  lane :build do |options|
    carthage(
      command: "bootstrap",
      platform: "iOS",
      cache_builds: true
    )
    increment_build_number
    gym(
      scheme: "hairfolio",
      clean: true,
      silent: true,
      include_bitcode: false
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    increment_version_number(
      bump_type: "patch" # Automatically increment patch version number
    )
    build
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    increment_version_number(
      bump_type: "minor" # Automatically increment patch version number
    )
    build
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions