import { Navigation } from 'react-native-navigation';
import ProductTagModal from './components/post/ProductTagModal';
import AddBlackBook from './containers/AddBlackBook';
import AddLink from './containers/AddLink';
import AddServicePageOne from './containers/AddServicePageOne';
import AddServicePageThree from './containers/AddServicePageThree';
import AddServicePageTwo from './containers/AddServicePageTwo';
import AlbumPage from './containers/AlbumPage';
import BasicInfo from './containers/BasicInfo';
import BlackBook from './containers/BlackBook';
import BrandAddress from './containers/BrandAddress';
import BrandInfo from './containers/BrandInfo';
import BankAccountList from './containers/BankAccountList';
import CartAddress from './containers/CartAddress';
import CartList from './containers/CartList';
import CardList from './containers/CardList';
import CategoryProductsList from './containers/CategoryProductsList';
import CategoryRelatedProductsList from './containers/CategoryRelatedProductList';
import ChangePassword from './containers/ChangePassword';
import CheckoutMethods from './containers/CheckoutMethods';
import Comments from './containers/Comments';
import ConfirmOrder from './containers/ConfirmOrder';
import ContactDetails from './containers/ContactDetails';
import CouponList from './containers/CouponList';
import CreatePost from './containers/CreatePost';
import EditCustomer from './containers/EditCustomer';
import EditCustomerAddress from './containers/EditCustomerAddress';
import Favourites from './containers/Favourites';
import FavouritesGridList from './containers/FavouritesGridList';
import Feed from './containers/Feed';
import FilterPage from './containers/FilterPage';
import FilterProduct from './containers/FilterProduct';
import FilterProductForProductTag from './containers/FilterProductForProductTag';
import ForgotPassword from './containers/ForgottenPassword';
import Gallery from './containers/GalleryPage';
import HairfolioPosts from './containers/HairfolioPosts';
import Login from './containers/Login';
import LoginEmail from './containers/LoginEmail';
import LoginOAuth from './containers/LoginOAuth';
import MessageDetails from './containers/MessageDetails';
import Messages from './containers/Messages';
import Notifications from './containers/Notifications';
import OrderHistory from './containers/OrderHistory';
import OrderDetails from './containers/OrderDetails';
import PostDetails from './containers/PostDetails';
import PostFilter from './containers/PostFilter';
import PostsGridList from './containers/PostsGridList';
import PreviewOrder from './containers/PreviewOrder';
import ProductDetail from './containers/ProductDetail';
import ProductModule from './containers/ProductModule';
import ProductViewAll from './containers/ProductViewAll';
import Profile from './containers/Profile';
import ReferAFriend from './containers/ReferAFriend';
import ReferAndEarn from './containers/ReferAndEarn';
import Register from './containers/Register';
import Register2 from './containers/Register2';
import RelatedProductViewAll from './containers/RelatedProductViewAll';
import SalonAddSP from './containers/SalonAddSP';
import SalonInfo from './containers/SalonInfo';
import SalonSP from './containers/SalonSP';
import SalonStylists from './containers/SalonStylists';
import Search from './containers/Search';
import SearchSeeAll from './containers/SearchSeeAll';
import SearchDetails from './containers/SearchDetails';
import Share from './containers/Share';
import StarGivers from './containers/StarGivers';
import StylistAddEducation from './containers/StylistAddEducation';
import StylistCertificates from './containers/StylistCertificates';
import StylistEducation from './containers/StylistEducation';
import StylistInfo from './containers/StylistInfo';
import StylistPlaceOfWork from './containers/StylistPlaceOfWork';
import StylistProductExperience from './containers/StylistProductExperience';
import TagPosts from './containers/TagPosts';
import TrackMyOrder from './containers/TrackMyOrder';
import UpdateAddress from './containers/UpdateAddress';
import ViewAllProductsDetailList from './containers/ViewAllProductsDetailList';
import Wallet from './containers/Wallet';
import WishList from './containers/WishList';
import WithDrawAmount from './containers/WithDrawAmount';
import WriteMessage from './containers/WriteMessage';


export const registerScreens = ()  => {
  Navigation.registerComponent('hairfolio.Register', () => Register);
  Navigation.registerComponent('hairfolio.Login', () => Login);
  Navigation.registerComponent('hairfolio.LoginEmail', () => LoginEmail);
  Navigation.registerComponent('hairfolio.Register2', () => Register2);
  Navigation.registerComponent('hairfolio.BasicInfo', () => BasicInfo);
  Navigation.registerComponent('hairfolio.LoginOAuth', () => LoginOAuth);
  Navigation.registerComponent('hairfolio.StylistInfo', () => StylistInfo);
  Navigation.registerComponent('hairfolio.StylistEducation', () => StylistEducation);
  Navigation.registerComponent('hairfolio.StylistCertificates', () => StylistCertificates);
  Navigation.registerComponent('hairfolio.StylistPlaceOfWork', () => StylistPlaceOfWork);
  Navigation.registerComponent('hairfolio.StylistProductExperience', () => StylistProductExperience);
  Navigation.registerComponent('hairfolio.SalonAddSP', () => SalonAddSP);
  Navigation.registerComponent('hairfolio.SalonSP', () => SalonSP);
  Navigation.registerComponent('hairfolio.StylistAddEducation', () => StylistAddEducation);
  Navigation.registerComponent('hairfolio.SalonInfo', () => SalonInfo);
  Navigation.registerComponent('hairfolio.BrandInfo', () => BrandInfo);
  Navigation.registerComponent('hairfolio.Feed', () => Feed);
  Navigation.registerComponent('hairfolio.Search', () => Search);
  Navigation.registerComponent('hairfolio.SearchSeeAll', () => SearchSeeAll);
  Navigation.registerComponent('hairfolio.Favourites', () => Favourites);
  Navigation.registerComponent('hairfolio.Profile', () => Profile);
  Navigation.registerComponent('hairfolio.Messages', () => Messages);
  Navigation.registerComponent('hairfolio.WriteMessage', () => WriteMessage);
  Navigation.registerComponent('hairfolio.MessageDetails', () => MessageDetails);
  Navigation.registerComponent('hairfolio.PostDetails', () => PostDetails);
  Navigation.registerComponent('hairfolio.SearchDetails', () => SearchDetails);
  Navigation.registerComponent('hairfolio.TagPosts', () => TagPosts);
  Navigation.registerComponent('hairfolio.Comments', () => Comments);
  Navigation.registerComponent('hairfolio.StarGivers', () => StarGivers);
  Navigation.registerComponent('hairfolio.HairfolioPosts', () => HairfolioPosts);
  Navigation.registerComponent('hairfolio.BlackBook', () => BlackBook);
  Navigation.registerComponent('hairfolio.ContactDetails', () => ContactDetails);
  Navigation.registerComponent('hairfolio.CreatePost', () => CreatePost);
  Navigation.registerComponent('hairfolio.Gallery', () => Gallery);
  Navigation.registerComponent('hairfolio.Share', () => Share);
  Navigation.registerComponent('hairfolio.AlbumPage', () => AlbumPage);
  Navigation.registerComponent('hairfolio.PostFilter', () => PostFilter);
  Navigation.registerComponent('hairfolio.FilterPage', () => FilterPage);
  Navigation.registerComponent('hairfolio.AddServicePageOne', () => AddServicePageOne);
  Navigation.registerComponent('hairfolio.AddServicePageTwo', () => AddServicePageTwo);
  Navigation.registerComponent('hairfolio.AddServicePageThree', () => AddServicePageThree);
  Navigation.registerComponent('hairfolio.AddLink', () => AddLink);
  Navigation.registerComponent('hairfolio.ForgotPassword', () => ForgotPassword);
  Navigation.registerComponent('hairfolio.EditCustomer', () => EditCustomer);
  Navigation.registerComponent('hairfolio.EditCustomerAddress', () => EditCustomerAddress);
  Navigation.registerComponent('hairfolio.ChangePassword', () => ChangePassword);
  Navigation.registerComponent('hairfolio.SalonStylists', () => SalonStylists);
  Navigation.registerComponent('hairfolio.AddBlackBook', () => AddBlackBook);
  Navigation.registerComponent('hairfolio.BrandAddress', () => BrandAddress);
  Navigation.registerComponent('hairfolio.ProductModule', () => ProductModule);
  Navigation.registerComponent('hairfolio.CartList', () => CartList);
  Navigation.registerComponent('hairfolio.FilterProduct', () => FilterProduct);
  Navigation.registerComponent('hairfolio.FilterProductForProductTag', () => FilterProductForProductTag);
  Navigation.registerComponent('hairfolio.ProductViewAll', () => ProductViewAll);
  Navigation.registerComponent('hairfolio.ProductDetail', () => ProductDetail);
  Navigation.registerComponent('hairfolio.CategoryProductsList', () => CategoryProductsList);
  Navigation.registerComponent('hairfolio.CartAddress', () => CartAddress);
  Navigation.registerComponent('hairfolio.PreviewOrder', () => PreviewOrder);  
  Navigation.registerComponent('hairfolio.ConfirmOrder', () => ConfirmOrder);
  Navigation.registerComponent('hairfolio.OrderHistory', () => OrderHistory);
  Navigation.registerComponent('hairfolio.Wallet', () => Wallet);
  Navigation.registerComponent('hairfolio.WishList', () => WishList)
  Navigation.registerComponent('hairfolio.CheckoutMethods', () => CheckoutMethods)
  Navigation.registerComponent('hairfolio.ReferAFriend', () => ReferAFriend);
  Navigation.registerComponent('hairfolio.ViewAllProductsDetailList', () => ViewAllProductsDetailList);
  Navigation.registerComponent('hairfolio.FavouritesGridList',() => FavouritesGridList)
  Navigation.registerComponent('hairfolio.Notifications',() => Notifications)
  Navigation.registerComponent('hairfolio.PostsGridList',() => PostsGridList)
  Navigation.registerComponent('hairfolio.TrackMyOrder',() => TrackMyOrder)
  Navigation.registerComponent('hairfolio.ReferAndEarn',() => ReferAndEarn)
  Navigation.registerComponent('hairfolio.ProductTagModal',() => ProductTagModal);
  Navigation.registerComponent('hairfolio.CouponList',() => CouponList);
  Navigation.registerComponent('hairfolio.CardList',() => CardList);
  Navigation.registerComponent('hairfolio.UpdateAddress',() => UpdateAddress);
  Navigation.registerComponent('hairfolio.OrderDetails',() => OrderDetails);
  Navigation.registerComponent('hairfolio.WithDrawAmount',() => WithDrawAmount);
  Navigation.registerComponent('hairfolio.BankAccountList',() => BankAccountList);
  Navigation.registerComponent('hairfolio.CategoryRelatedProductsList',() => CategoryRelatedProductsList);
  Navigation.registerComponent('hairfolio.RelatedProductViewAll',() => RelatedProductViewAll);
};