export const environment = ({environment}) => ({
  environmentState: environment.state,
  environment: environment.environment,
  degreesState: environment.degreesState,
  degrees: environment.degrees,
  servicesState: environment.servicesState,
  services: environment.services,
  categoriesState: environment.categoriesState,
  categories: environment.categories,
  certificatesState: environment.certificatesState,
  certificates: environment.certificates,
  experiencesState: environment.experiencesState,
  experiences: environment.experiences,
  experiencesNextPage: environment.experiencesNextPage,
});
